name: Workflow to print arg in terminal
on:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup python
              uses: actions/setup-python@v2 
              with:
                python-version: '3.x'
            
            - name: Set up Helm
              uses: azure/setup-helm@v2
              with:
                version: 'latest'    

            - name: Install dependencies
              run: python -m pip install --upgrade pip
           

            - name: Run python script with some input to print
              run: python script.py Hi "Good Morning" "How are you" Bye





